[window.padding]
x = 15
y = 10

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
#background = '#1a1b26'
background = '#1b1b1b'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[font]
size = 10.0

[font.bold]
family = "HackNerdFontPropo"
style = "Bold"

[font.bold_italic]
family = "HackNerdFontPropo"
style = "Bold Italic"

[font.italic]
family = "HackNerdFontPropo"
style = "Italic"

[font.normal]
family = "HackNerdFontPropo"
style = "Regular"
